---
title: "August&On_Variable_by_Variable"
output: html_document
---

```{r}
# Keep a copy of the original to make comparisons against
original <- after_health_assess
```

## Site names

Correct capitalization inconsistencies with CPVT and Sugar River.

```{r}
# Correct capitalization inconsistencies with CPVT and Sugar River
after_health_assess <- after_health_assess %>%
  mutate(site_name = case_when(
    site_name == "Cpvt" ~ "CPVT",
    str_detect(site_name, "SR") ~ "SR", # Some of the SR's include the individual by accident, e.g. "SR-10"
    TRUE ~ site_name # Otherwise, keep name the same
  ))
```

# Numeric NA renamings

## GPS
Presence of several different ways of saying an NA. Here I clarify them all to actual NA values.

```{r}
june_health_assess <- june_health_assess %>% mutate(
  gps_north = case_when(
    gps_north == 0 ~ NA,
    gps_north == "Na" ~ NA,
    gps_north == "N/A" ~ NA,
    gps_north == "X" ~ NA,
    TRUE ~ gps_north
  ),
  gps_west = case_when(
    gps_west == 0 ~ NA,
    gps_west == "Na" ~ NA,
    gps_west == "N/A" ~ NA,
    gps_west == "X" ~ NA,
    TRUE ~ gps_west
  )
)

```





