health_assess_2024$plant_height_ft <- as.numeric(health_assess_2024$plant_height_ft)
health_assess_2024$dbh_cm <- as.numeric(health_assess_2024$dbh_cm)
health_assess_2024$percent_live_canopy <- as.numeric(health_assess_2024$percent_live_canopy)
health_assess_2024$base_canker_area <- as.numeric(health_assess_2024$base_canker_area)
health_assess_2024$trunk_canker_area <- as.numeric(health_assess_2024$trunk_canker_area)